### PR TITLE
Correct compilation warnings for 'int' casts with correct types

### PR DESCRIPTION
**Pull request by huguesdpdn-aerospace**
Fix a potential error on some specific architectures (aka devices with `sizeof(int)` different of `sizeof(ssize_t)`) where a `size_t` or `ssize_t` are not actually a real `int`. When dealing (subtracting or adding values) with `size_t` with negative value, `int `you should not be use but rather its dedicated opposite version, aka the signed one: `ssize_t`

Also, when dealing with `tellg`, actually it returns a `streampos` (see [C++ Reference | std::streampos](https://cplusplus.com/reference/ios/streampos/) ) which should not be incremented or decremented with any integer. Instead, a dedicated method should be called by using `std::streamoff` for that in the class (see [C++ Reference | std::streamoff](https://cplusplus.com/reference/ios/streamoff/) )

### CODE REVIEW

**Review by aiksiongkoh — APPROVED** [review]

**Comment by aiksiongkoh** [comment]
Windows build failed. @huguesdpdn-aerospace please check. Thanks.

**Comment by huguesdpdn-aerospace** [comment]
Indeed Windows do not recognise `ssize_t` and I don't have any computer running not under Windows so I added a pre-processor macro with a `typedef` since `SSIZE_T` exists on Windows but not on Unix. Would need you @aiksiongkoh to execute the workflow and check if it compiles.

**Comment by aiksiongkoh** [comment]
@huguesdpdn-aerospace Please see build failures due to typo. Thanks.

**Comment by aiksiongkoh** [comment]
@huguesdpdn-aerospace Please remove the extra || in line below
   15 | #if defined(WIN32) || defined(_WIN32) ||  || defined(__WIN32__) || defined(__NT__)

**Comment by huguesdpdn-aerospace** [comment]
Hello @aiksiongkoh , sorry I was in vacation. In addition, it was a stupid and easy typo to fix, sorry :/

Let's see if it compiles on all platform tonight.

**Review by aiksiongkoh — APPROVED** [review]

**Comment by huguesdpdn-aerospace** [comment]
Hi @aiksiongkoh , again, couldn't test under Windows, and it seems that the macro `SSIZE_T` was not defined because under Windows, for `SSIZE_T` , documentation specify that we need to include [Windows Data Types](https://learn.microsoft.com/fr-fr/windows/win32/winprog/windows-data-types)

A copy of the declared data can be found here: [Windows 10 SDK - baseTsd.h](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/shared/basetsd.h)

Need a new approval to re-execute the compilation tests

**Review by aiksiongkoh — APPROVED** [review]

**Pull request merged**
